### PR TITLE
Setting unique cookie for each authentication request

### PR DESCRIPTION
**Pull request by tushargupta51**

### CODE REVIEW

**Comment by dontbesorry80** [comment]
Hi, This seemed the perfect solution for what I needed. However it seems to keep appending the cookies to the client. So after a while I got an error saying "Bad Request - Request to long, HTTP Error 400 The size of the request headers is too long" It seems to append ALL the nonce tokens into the header.

Is there a way to tweak this code to stop this from happening?

Also, When I try to set RequireNonce = false, I just get an error saying "Invalid_request".

Any help would be appreciated?

**Comment by dstrockis** [comment]
Hey @dontbesorry80... The middleware should be clearing the nonce cookies each time a response is received from AAD.  If you see an accumulation of nonce cookies, something's not quite right.  If you want to mail or attach a trace (Fiddler, etc) I would be happy to try and help diagnose.

**Comment by dontbesorry80** [comment]
Nevermind.. The problem is with mutli-tabbed browsing. When one tab logs in fully and deletes the cookies etc. the other page then has the problem. However I just caught the error and re-directed.
Thanks for your help

**Comment by jahansha** [comment]
Can you share what needs to be done to clear nonce cookies

**Pull request closed without merging**
